#!/bin/bash

#Coded by Krypt0N

items=("https://www.youtube.com/watch?v=YnmEePUXLRs" "https://www.youtube.com/watch?v=3vVSBLkpO-8" "https://www.youtube.com/watch?v=iPKJUzkTt6Y" "https://www.youtube.com/watch?v=5soixb2U6xM" "https://www.youtube.com/watch?v=gYCTXzOTnXg" "https://www.youtube.com/watch?v=WMOd6jz548Y" "https://www.youtube.com/watch?v=zKFzKIa_pIM" "https://www.youtube.com/watch?v=cULQhvuq1Zc" "https://www.youtube.com/watch?v=pqrUQrAcfo4" "https://www.youtube.com/watch?v=pQsF3pzOc54")

size=${#items[@]}
randomindex=$(($RANDOM % $size))

echo -e "\e[1;4;35mIf you want to stop playing press (CTRL + C)"

mpv ${items[$randomindex]}

CANCION=${items[$randomindex]}

if [ "$CANCION" == "https://www.youtube.com/watch?v=YnmEePUXLRs" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: The Less i Know the Better - Tame Impala" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo
fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=3vVSBLkpO-8" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Baby Im Yours - Breakbot" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=iPKJUzkTt6Y" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: The Look - Metronomy" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=5soixb2U6xM" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Affection - Cigarettes After Sex" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=gYCTXzOTnXg" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Boulevard of Broken Dreams - Green Day" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=WMOd6jz548Y" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Breezeblocks - Alt-J" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=zKFzKIa_pIM" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Chlorine - Twenty One Pilots" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=cULQhvuq1Zc" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Sweater Weather - The Neighbourhood" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=pqrUQrAcfo4" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Do I Wanna Know? - Arctic Monkeys" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=pQsF3pzOc54" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Chamber of Reflection - Mac DeMarco" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi


echo -e "\e[93mDo you wanna listen another song?"
 select yn in "Yes" "No"; do
    case $yn in
        Yes ) bash MRIndie; exit;;

         No ) 
	     echo -e "\e[94mDo you wanna listen another genre?"
             	select yn in "Yes" "No"; do
               		case $yn in
                 		Yes ) bash MUDATOR.sh; exit;;
                 		No ) clear; echo "See you later!" | lolcat -a; exit;;
                 		* ) echo "Please choice a valid option!";;
                   			esac
                                        	done;;	 

	* ) echo "Please choice a valid option!";;
    esac
done



	



